[package]
name = "rust-os"
version = "0.1.0"
authors = ["Til Blechschmidt <til@blechschmidt.de>"]

["lib"]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"
bitflags = "0.7.0"
